### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by sinchb** [sigrand/OpenONVIF#3]
I have successfully installed gsoap(version: 2.8.16). When I run `cmake ../OnvifSDK`, it failed:

```
linuxdev3@linuxdev3:~/workspace/OpenONVIF/OnvifSDK-build$ cmake ../OnvifSDK
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:6 (message):
  Provide SIGRLOG_OUTPUT


-- Configuring incomplete, errors occurred!
See also "/home/linuxdev3/workspace/OpenONVIF/OnvifSDK-build/CMakeFiles/CMakeOutput.log".

```

Please, is there something wrong?
OS: ubuntu 14.04

**Comment by gaurav5670** [comment]
I am also getting the same error, any fixes for it?

gaurav@gaurav-HP-EliteDesk-800-G2-TWR:~/researchONVIF/OpenONVIF-master$ sudo make
Scanning dependencies of target OnvifSDK
[  2%] Building CXX object CMakeFiles/OnvifSDK.dir/source/BaseServer.cpp.o
In file included from /home/gaurav/researchONVIF/OpenONVIF-master/OnvifSDK/include/BaseServer.h:16:0,
                 from /home/gaurav/researchONVIF/OpenONVIF-master/OnvifSDK/source/BaseServer.cpp:2:
/home/gaurav/researchONVIF/OpenONVIF-master/OnvifSDK/include/DeviceServiceImpl.h:7:37: fatal error: WebDeviceBindingService.h: No such file or directory
 #include "WebDeviceBindingService.h"
                                     ^
compilation terminated.
make[2]: *** [CMakeFiles/OnvifSDK.dir/source/BaseServer.cpp.o] Error 1
make[1]: *** [CMakeFiles/OnvifSDK.dir/all] Error 2
make: *** [all] Error 2

**Comment by d1f** [comment]
The project closed and not supported.
